# Required substituion variables:
# - _GH_WEBHOOKS_TEST_DOMAIN


steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - docker build -t gcr.io/$PROJECT_ID/gh-webhooks-test:${TAG_NAME} -f Dockerfile .

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gh-webhooks-test:${TAG_NAME}"]

  # Deploy service image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - >
        gcloud
        run deploy ${TAG_NAME}-gh-webhooks-test
        --cpu 1
        --memory 256M
        --max-instances 5
        --image gcr.io/$PROJECT_ID/gh-webhooks-test:${TAG_NAME}
        --region europe-west1
        --platform managed
        --allow-unauthenticated
        --set-env-vars WEBHOOK_SECRET=$$WEBHOOK_SECRET
    secretEnv:
      - WEBHOOK_SECRET

  # Apply domain mapping. Cheap idempotency by ignoring failures.
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - >
        gcloud
        beta run domain-mappings create
        --service ${TAG_NAME}-gh-webhooks-test
        --domain ${TAG_NAME}.${_GH_WEBHOOKS_TEST_DOMAIN}
        --region europe-west1
        || true


availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GH_WEBHOOK_TEST_WEBHOOK_SECRET/versions/latest
      env: "WEBHOOK_SECRET"
